topLevelString = "TLS"
topLevelLong = 100
topLevelDouble = 1.11
topLevelTime = "25.08.2022 16:16:57 CEST"

[firstLevel]
levelString = "LS"
levelLong = 200

[secondLevel]
levelDouble = 2.22
levelTime = "25.08.2022 16:16:57 CEST"


