topLevelString = "TLS"
topLevelLong = 100
topLevelDouble = 1.11
topLevelTime = "26.08.2022 10:23:30 CEST"

[firstLevel]
levelString = "LS"
levelLong = 200

[secondLevel]
levelDouble = 2.22
levelTime = "26.08.2022 10:23:30 CEST"

[buildInfo]
version = "0.2.0"
branch = "main"
commitHash = "8f54f07a0ecd6d553ccdf8a64c68956fe81e7821"


